### ISSUE TITLE
Add Bottom and Side walls

### ISSUE THREAD

**Issue by MarosPataky** [scscgit/TukeQuest#1]
Walls will be displayed with some texture (TUKE-theme).

**Comment by scscgit** [comment]
Side walls will be auto-generated (spawned), or they will be static with infinite length / or absolute position on screen? Which solution is easier?

For simplicity, walls can extend [RectangleActor](https://github.com/scscgit/TukeQuest/blob/master/core/src/sk/tuke/gamedev/iddqd/tukequest/actors/RectangleActor.java) class.

**Comment by scscgit** [comment]
For now, they are not infinite as it depends on [infinite scroll](https://github.com/scscgit/TukeQuest/issues/7).
