### ISSUE TITLE
Create Player actor

### ISSUE THREAD

**Issue by MarosPataky** [scscgit/TukeQuest#2]

**Comment by scscgit** [comment]
Example of multi-platform input usage is in https://github.com/scscgit/TukeQuest/blob/master/core/src/sk/tuke/gamedev/iddqd/tukequest/actors/ExampleActor.java#L32 - that actor can be safely deleted when this task is finished. Rectangle shape is enough for the Player.

**Comment by scscgit** [comment]
Movement implementation is solved in issue [Create Player controller (move with arrows etc...) ](https://github.com/scscgit/TukeQuest/issues/3). Rectangle shape is enough for the Player, animation is preferred (with multiple states).
