### ISSUE TITLE
Add player sound effects.

### ISSUE THREAD

**Issue by scscgit** [scscgit/TukeQuest#28]
At least for jumping and falling.

**Comment by JakubRuzicka** [comment]
jump https://freesound.org/people/acebrian/sounds/380471/

**Comment by JakubRuzicka** [comment]
Bonus https://freesound.org/people/Scrampunk/sounds/345299/

**Comment by scscgit** [comment]
Added second [Binas sound from a lecture](https://github.com/scscgit/TukeQuest/commit/266db6389301e158b1ab7679f43cd0bff237f0de) and the support for varying Teacher sound durations.
