### ISSUE TITLE
Create Player controller (move with arrows etc...)

### ISSUE THREAD

**Issue by MarosPataky** [scscgit/TukeQuest#3]

**Comment by scscgit** [comment]
Example of multi-platform input usage is in [ExampleActor#act](https://github.com/scscgit/TukeQuest/blob/master/core/src/sk/tuke/gamedev/iddqd/tukequest/actors/ExampleActor.java#L32) - that actor can be safely deleted when this task is finished. Rectangle shape is enough for the Player.

**Comment by scscgit** [comment]
We will possibly need an on-screen GUI for the arrows + jump in the Android platform? My ExampleActor only splits the screen to 2 halves acting as right vs. left.

**Comment by scscgit** [comment]
Jumping [fixed](https://github.com/scscgit/TukeQuest/commit/bd4ed6bbf79f64e2f663e2bd42e658a66c2afda3) by allowing it only when linear y velocity is < 0.1f, this condition can be improved later on. The issue [#16 jumping condition](https://github.com/scscgit/TukeQuest/issues/16) will fix the problem.

**Comment by scscgit** [comment]
The controller will have to use new animations based on movement left/right/jump. Sprite "player.png" offers them all. (New png will be supplied by [Issue #17](https://github.com/scscgit/TukeQuest/issues/17).)

**Comment by scscgit** [comment]
The movement should support WSAD too. The camera debug should override this control, it will probably have its own Camera Controller. The Controller can be Actor and use act() while being added to the Screen.
