### ISSUE TITLE
Create platform Actors  (just class + texture)

### ISSUE THREAD

**Issue by MarosPataky** [scscgit/TukeQuest#4]

**Comment by scscgit** [comment]
For simplicity, platforms can extend [RectangleActor](https://github.com/scscgit/TukeQuest/blob/master/core/src/sk/tuke/gamedev/iddqd/tukequest/actors/RectangleActor.java) class.

**Comment by scscgit** [comment]
[Platform collision from below disabled](https://github.com/scscgit/TukeQuest/commit/b4c7a08b04bb2af78721443e7127115576160f34)

**Comment by MarosPataky** [comment]
Implemented only hardcoded platform with donwloaded texture for now.

**Comment by scscgit** [comment]
Third platform is under ground, otherwise ok.
