### ISSUE TITLE
Implement platform generation logic

### ISSUE THREAD

**Issue by MarosPataky** [scscgit/TukeQuest#5]

**Comment by scscgit** [comment]
Task depends on [Create platform Actors (just class + texture)](https://github.com/scscgit/TukeQuest/issues/4)

**Comment by scscgit** [comment]
[This](https://github.com/scscgit/TukeQuest/commit/ecc835710482da1dae7848fe1559147950f63d9c) and [this](https://github.com/scscgit/TukeQuest/commit/84a91e33ced1c865b564f5db24e5a54a749d16c7) commit finished the task.
