### ISSUE TITLE
Create Menu screen

### ISSUE THREAD

**Issue by scscgit** [scscgit/TukeQuest#9]

**Comment by scscgit** [comment]
[TextButton example in a third party project](https://github.com/playerony/IcyTower.LibGDX/blob/55ff9ee77cbe92c96a753ecfb21e87d740437567/core/src/com/mygdx/game/com/mygdx/game/screens/MenuScreen.java#L73)

**Comment by scscgit** [comment]
Basic buttons I expect: start game, exit game, maybe options like turn on/off the music. Background can be animated.

**Comment by scscgit** [comment]
My attempt at turning the first Menu screen into a Pause Menu triggered by ESC failed, because the libgdx lifecycle is more complicated and it only restarted the game anyway, so we can skip that feature. [Feature branch pause-menu contains this old attempt](https://github.com/scscgit/TukeQuest/commit/82a4cec657e4e926a99d3aae403d80b234a4bd38).

**Comment by scscgit** [comment]
Reporting a related bug on master branch: conflict with Pause Screen. (One possible fix would be not allowing pause in the menu.)

![image](https://cloud.githubusercontent.com/assets/3118390/24841245/3378bfae-1d80-11e7-9d4f-a27df75ab22e.png)

**Comment by Joseph5610** [comment]
Fixed.
